/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    principles: Principle;
    faqs: Faq;
    ingredients: Ingredient;
    benefits: Benefit;
    trustItems: TrustItem;
    shippingInfo: ShippingInfo;
    trustBadges: TrustBadge;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    principles: PrinciplesSelect<false> | PrinciplesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    benefits: BenefitsSelect<false> | BenefitsSelect<true>;
    trustItems: TrustItemsSelect<false> | TrustItemsSelect<true>;
    shippingInfo: ShippingInfoSelect<false> | ShippingInfoSelect<true>;
    trustBadges: TrustBadgesSelect<false> | TrustBadgesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'AUD' | null;
  accessToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        variantOption?: (number | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  /**
   * Select FAQs to display on this product page.
   */
  faqs?: (number | Faq)[] | null;
  /**
   * Heading text for the "Full formulation breakdown" accordion section.
   */
  ingredientsHeading?: string | null;
  /**
   * Select ingredients to display in the formulation breakdown.
   */
  ingredients?:
    | {
        ingredient: number | Ingredient;
        /**
         * e.g., '250mg', '100mcg', '2 capsules'
         */
        quantity: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional text displayed below the ingredient list (e.g. 'Other Ingredients: ...').
   */
  otherIngredientsText?: string | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInAUDEnabled?: boolean | null;
  priceInAUD?: number | null;
  relatedProducts?: (number | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  categories?: (number | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  content: (
    | AboutCtaBlock
    | AboutFounderBlock
    | AboutHeroBlock
    | AboutPhilosophyBlock
    | AboutPrinciplesBlock
    | AboutTrustBlock
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
    | VialityHeroBlock
    | VialityPhilosophyBlock
    | VialityFeaturedProductsBlock
    | VialityTrustBlock
    | VialityWaitlistBlock
    | VialityShippingBlock
    | VialityComplianceBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutCtaBlock".
 */
export interface AboutCtaBlock {
  heading?: string | null;
  body?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  complianceText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutFounderBlock".
 */
export interface AboutFounderBlock {
  label?: string | null;
  quote?: string | null;
  signature?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutFounder';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock".
 */
export interface AboutHeroBlock {
  label?: string | null;
  heading?: string | null;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutPhilosophyBlock".
 */
export interface AboutPhilosophyBlock {
  label?: string | null;
  heading?: string | null;
  body?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  imageLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutPhilosophy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutPrinciplesBlock".
 */
export interface AboutPrinciplesBlock {
  label?: string | null;
  heading?: string | null;
  items?: (number | Principle)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutPrinciples';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles".
 */
export interface Principle {
  id: number;
  title: string;
  slug: string;
  displayNumber: string;
  body: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutTrustBlock".
 */
export interface AboutTrustBlock {
  label?: string | null;
  heading?: string | null;
  body?: string | null;
  image?: (number | null) | Media;
  imageLabel?: string | null;
  buttonLabel?: string | null;
  items?: (number | TrustItem)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutTrust';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trustItems".
 */
export interface TrustItem {
  id: number;
  title: string;
  slug: string;
  description: string;
  type: 'home' | 'about';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityHeroBlock".
 */
export interface VialityHeroBlock {
  tagline?: string | null;
  title?: string | null;
  subtext?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  media?:
    | {
        mediaItem?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  scrollLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vialityHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityPhilosophyBlock".
 */
export interface VialityPhilosophyBlock {
  body?: string | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'vialityPhilosophy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityFeaturedProductsBlock".
 */
export interface VialityFeaturedProductsBlock {
  heading?: string | null;
  shopAllLabel?: string | null;
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vialityFeaturedProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityTrustBlock".
 */
export interface VialityTrustBlock {
  heading?: string | null;
  body?: string | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    label: string;
  };
  items?: (number | TrustItem)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vialityTrust';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityWaitlistBlock".
 */
export interface VialityWaitlistBlock {
  heading?: string | null;
  body?: string | null;
  placeholder?: string | null;
  buttonLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vialityWaitlist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityShippingBlock".
 */
export interface VialityShippingBlock {
  items?: (number | ShippingInfo)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vialityShipping';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingInfo".
 */
export interface ShippingInfo {
  id: number;
  label: string;
  slug: string;
  detail: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityComplianceBlock".
 */
export interface VialityComplianceBlock {
  text?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'vialityCompliance';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  slug: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  slug: string;
  dose: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInAUDEnabled?: boolean | null;
  priceInAUD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'AUD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'AUD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benefits".
 */
export interface Benefit {
  id: number;
  title: string;
  slug: string;
  body: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trustBadges".
 */
export interface TrustBadge {
  id: number;
  label: string;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  principles?: {
    /**
     * Allow clients to find principles.
     */
    find?: boolean | null;
    /**
     * Allow clients to create principles.
     */
    create?: boolean | null;
    /**
     * Allow clients to update principles.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete principles.
     */
    delete?: boolean | null;
  };
  faqs?: {
    /**
     * Allow clients to find faqs.
     */
    find?: boolean | null;
    /**
     * Allow clients to create faqs.
     */
    create?: boolean | null;
    /**
     * Allow clients to update faqs.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete faqs.
     */
    delete?: boolean | null;
  };
  ingredients?: {
    /**
     * Allow clients to find ingredients.
     */
    find?: boolean | null;
    /**
     * Allow clients to create ingredients.
     */
    create?: boolean | null;
    /**
     * Allow clients to update ingredients.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete ingredients.
     */
    delete?: boolean | null;
  };
  benefits?: {
    /**
     * Allow clients to find benefits.
     */
    find?: boolean | null;
    /**
     * Allow clients to create benefits.
     */
    create?: boolean | null;
    /**
     * Allow clients to update benefits.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete benefits.
     */
    delete?: boolean | null;
  };
  trustItems?: {
    /**
     * Allow clients to find trustItems.
     */
    find?: boolean | null;
    /**
     * Allow clients to create trustItems.
     */
    create?: boolean | null;
    /**
     * Allow clients to update trustItems.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete trustItems.
     */
    delete?: boolean | null;
  };
  shippingInfo?: {
    /**
     * Allow clients to find shippingInfo.
     */
    find?: boolean | null;
    /**
     * Allow clients to create shippingInfo.
     */
    create?: boolean | null;
    /**
     * Allow clients to update shippingInfo.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete shippingInfo.
     */
    delete?: boolean | null;
  };
  trustBadges?: {
    /**
     * Allow clients to find trustBadges.
     */
    find?: boolean | null;
    /**
     * Allow clients to create trustBadges.
     */
    create?: boolean | null;
    /**
     * Allow clients to update trustBadges.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete trustBadges.
     */
    delete?: boolean | null;
  };
  forms?: {
    /**
     * Allow clients to find forms.
     */
    find?: boolean | null;
    /**
     * Allow clients to create forms.
     */
    create?: boolean | null;
    /**
     * Allow clients to update forms.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete forms.
     */
    delete?: boolean | null;
  };
  formSubmissions?: {
    /**
     * Allow clients to find form-submissions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create form-submissions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update form-submissions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete form-submissions.
     */
    delete?: boolean | null;
  };
  addresses?: {
    /**
     * Allow clients to find addresses.
     */
    find?: boolean | null;
    /**
     * Allow clients to create addresses.
     */
    create?: boolean | null;
    /**
     * Allow clients to update addresses.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete addresses.
     */
    delete?: boolean | null;
  };
  variants?: {
    /**
     * Allow clients to find variants.
     */
    find?: boolean | null;
    /**
     * Allow clients to create variants.
     */
    create?: boolean | null;
    /**
     * Allow clients to update variants.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete variants.
     */
    delete?: boolean | null;
  };
  variantTypes?: {
    /**
     * Allow clients to find variantTypes.
     */
    find?: boolean | null;
    /**
     * Allow clients to create variantTypes.
     */
    create?: boolean | null;
    /**
     * Allow clients to update variantTypes.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete variantTypes.
     */
    delete?: boolean | null;
  };
  variantOptions?: {
    /**
     * Allow clients to find variantOptions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create variantOptions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update variantOptions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete variantOptions.
     */
    delete?: boolean | null;
  };
  products?: {
    /**
     * Allow clients to find products.
     */
    find?: boolean | null;
    /**
     * Allow clients to create products.
     */
    create?: boolean | null;
    /**
     * Allow clients to update products.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete products.
     */
    delete?: boolean | null;
  };
  carts?: {
    /**
     * Allow clients to find carts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create carts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update carts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete carts.
     */
    delete?: boolean | null;
  };
  orders?: {
    /**
     * Allow clients to find orders.
     */
    find?: boolean | null;
    /**
     * Allow clients to create orders.
     */
    create?: boolean | null;
    /**
     * Allow clients to update orders.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete orders.
     */
    delete?: boolean | null;
  };
  transactions?: {
    /**
     * Allow clients to find transactions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create transactions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update transactions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete transactions.
     */
    delete?: boolean | null;
  };
  payloadMcpApiKeys?: {
    /**
     * Allow clients to find payload-mcp-api-keys.
     */
    find?: boolean | null;
    /**
     * Allow clients to create payload-mcp-api-keys.
     */
    create?: boolean | null;
    /**
     * Allow clients to update payload-mcp-api-keys.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete payload-mcp-api-keys.
     */
    delete?: boolean | null;
  };
  payloadKv?: {
    /**
     * Allow clients to find payload-kv.
     */
    find?: boolean | null;
    /**
     * Allow clients to create payload-kv.
     */
    create?: boolean | null;
    /**
     * Allow clients to update payload-kv.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete payload-kv.
     */
    delete?: boolean | null;
  };
  payloadLockedDocuments?: {
    /**
     * Allow clients to find payload-locked-documents.
     */
    find?: boolean | null;
    /**
     * Allow clients to create payload-locked-documents.
     */
    create?: boolean | null;
    /**
     * Allow clients to update payload-locked-documents.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete payload-locked-documents.
     */
    delete?: boolean | null;
  };
  payloadPreferences?: {
    /**
     * Allow clients to find payload-preferences.
     */
    find?: boolean | null;
    /**
     * Allow clients to create payload-preferences.
     */
    create?: boolean | null;
    /**
     * Allow clients to update payload-preferences.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete payload-preferences.
     */
    delete?: boolean | null;
  };
  payloadMigrations?: {
    /**
     * Allow clients to find payload-migrations.
     */
    find?: boolean | null;
    /**
     * Allow clients to create payload-migrations.
     */
    create?: boolean | null;
    /**
     * Allow clients to update payload-migrations.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete payload-migrations.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'principles';
        value: number | Principle;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'benefits';
        value: number | Benefit;
      } | null)
    | ({
        relationTo: 'trustItems';
        value: number | TrustItem;
      } | null)
    | ({
        relationTo: 'shippingInfo';
        value: number | ShippingInfo;
      } | null)
    | ({
        relationTo: 'trustBadges';
        value: number | TrustBadge;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  content?:
    | T
    | {
        aboutCta?: T | AboutCtaBlockSelect<T>;
        aboutFounder?: T | AboutFounderBlockSelect<T>;
        aboutHero?: T | AboutHeroBlockSelect<T>;
        aboutPhilosophy?: T | AboutPhilosophyBlockSelect<T>;
        aboutPrinciples?: T | AboutPrinciplesBlockSelect<T>;
        aboutTrust?: T | AboutTrustBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        vialityHero?: T | VialityHeroBlockSelect<T>;
        vialityPhilosophy?: T | VialityPhilosophyBlockSelect<T>;
        vialityFeaturedProducts?: T | VialityFeaturedProductsBlockSelect<T>;
        vialityTrust?: T | VialityTrustBlockSelect<T>;
        vialityWaitlist?: T | VialityWaitlistBlockSelect<T>;
        vialityShipping?: T | VialityShippingBlockSelect<T>;
        vialityCompliance?: T | VialityComplianceBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutCtaBlock_select".
 */
export interface AboutCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  complianceText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutFounderBlock_select".
 */
export interface AboutFounderBlockSelect<T extends boolean = true> {
  label?: T;
  quote?: T;
  signature?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock_select".
 */
export interface AboutHeroBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutPhilosophyBlock_select".
 */
export interface AboutPhilosophyBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  body?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  image?: T;
  imageLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutPrinciplesBlock_select".
 */
export interface AboutPrinciplesBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutTrustBlock_select".
 */
export interface AboutTrustBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  body?: T;
  image?: T;
  imageLabel?: T;
  buttonLabel?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityHeroBlock_select".
 */
export interface VialityHeroBlockSelect<T extends boolean = true> {
  tagline?: T;
  title?: T;
  subtext?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  media?:
    | T
    | {
        mediaItem?: T;
        id?: T;
      };
  scrollLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityPhilosophyBlock_select".
 */
export interface VialityPhilosophyBlockSelect<T extends boolean = true> {
  body?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityFeaturedProductsBlock_select".
 */
export interface VialityFeaturedProductsBlockSelect<T extends boolean = true> {
  heading?: T;
  shopAllLabel?: T;
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityTrustBlock_select".
 */
export interface VialityTrustBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityWaitlistBlock_select".
 */
export interface VialityWaitlistBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  placeholder?: T;
  buttonLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityShippingBlock_select".
 */
export interface VialityShippingBlockSelect<T extends boolean = true> {
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VialityComplianceBlock_select".
 */
export interface VialityComplianceBlockSelect<T extends boolean = true> {
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles_select".
 */
export interface PrinciplesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  displayNumber?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  slug?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  dose?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benefits_select".
 */
export interface BenefitsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trustItems_select".
 */
export interface TrustItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingInfo_select".
 */
export interface ShippingInfoSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  detail?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trustBadges_select".
 */
export interface TrustBadgesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInAUDEnabled?: T;
  priceInAUD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  faqs?: T;
  ingredientsHeading?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        quantity?: T;
        id?: T;
      };
  otherIngredientsText?: T;
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInAUDEnabled?: T;
  priceInAUD?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  accessToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  principles?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  faqs?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  ingredients?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  benefits?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  trustItems?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  shippingInfo?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  trustBadges?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  forms?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  formSubmissions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  addresses?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  variants?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  variantTypes?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  variantOptions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  products?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  carts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  orders?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  transactions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  payloadMcpApiKeys?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  payloadKv?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  payloadLockedDocuments?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  payloadPreferences?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  payloadMigrations?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heroLabel?: string | null;
  heroHeading?: string | null;
  heroBody?: string | null;
  philosophyLabel?: string | null;
  philosophyHeading?: string | null;
  philosophyBody?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  philosophyImageLabel?: string | null;
  principlesLabel?: string | null;
  principlesHeading?: string | null;
  trustLabel?: string | null;
  trustHeading?: string | null;
  trustBody?: string | null;
  trustImageLabel?: string | null;
  trustButtonLabel?: string | null;
  founderLabel?: string | null;
  founderQuote?: string | null;
  founderSignature?: string | null;
  ctaHeading?: string | null;
  ctaBody?: string | null;
  ctaShopLabel?: string | null;
  ctaLabLabel?: string | null;
  complianceText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  siteTitle?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Brand wordmark shown top-left.
   */
  brandName?: string | null;
  /**
   * Short tagline below the wordmark.
   */
  brandDescription?: string | null;
  /**
   * Navigation links in the second column.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Social and contact links in the third column.
   */
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Privacy, Terms, etc. shown in the bottom bar.
   */
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Use {year} as a placeholder for the current year.
   */
  copyright?: string | null;
  /**
   * FDA disclaimer shown at the bottom. Newline-delimited.
   */
  complianceText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  defaultOGImage?: (number | null) | Media;
  /**
   * Upload an SVG for the site logo. SVGs render inline at any size without quality loss.
   */
  logo?: (number | null) | Media;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  benefitsLabelTemplate?: string | null;
  benefitsHeading?: string | null;
  usageRitualLabel?: string | null;
  usageRitualHeading?: string | null;
  usageRitualBody?: string | null;
  usageRitualDisclaimer?: string | null;
  verificationLabel?: string | null;
  verificationHeading?: string | null;
  verificationBody?: string | null;
  labReportLabel?: string | null;
  requestCOALabel?: string | null;
  completeRitualHeading?: string | null;
  productDisclaimer?: string | null;
  collectionLabel?: string | null;
  supplyLabel?: string | null;
  purchaseOptionLabel?: string | null;
  subscribeLabel?: string | null;
  /**
   * Discount percentage applied to the subscription price. Default: 10%.
   */
  subscribeDiscountPercent?: number | null;
  subscribeDetail?: string | null;
  oneTimeLabel?: string | null;
  quantityLabel?: string | null;
  buyNowLabel?: string | null;
  shippingText?: string | null;
  ingredientsHeading?: string | null;
  otherIngredientsText?: string | null;
  faqLabel?: string | null;
  faqHeading?: string | null;
  bankTransferEnabled?: boolean | null;
  bankTransferHeading?: string | null;
  bankTransferNote?: string | null;
  bankName?: string | null;
  accountName?: string | null;
  accountNumber?: string | null;
  routingNumber?: string | null;
  swiftCode?: string | null;
  loginWarning?: string | null;
  ordersLoginWarning?: string | null;
  alreadyLoggedInWarning?: string | null;
  accountHeading?: string | null;
  recentOrdersHeading?: string | null;
  recentOrdersDescription?: string | null;
  noOrdersText?: string | null;
  viewAllOrdersLabel?: string | null;
  ordersHeading?: string | null;
  allOrdersLabel?: string | null;
  orderNumberPrefix?: string | null;
  orderDateLabel?: string | null;
  totalLabel?: string | null;
  statusLabel?: string | null;
  itemsLabel?: string | null;
  itemUnavailableText?: string | null;
  shippingAddressLabel?: string | null;
  addressesHeading?: string | null;
  loginHeading?: string | null;
  loginDescription?: string | null;
  createAccountHeading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heroLabel?: T;
  heroHeading?: T;
  heroBody?: T;
  philosophyLabel?: T;
  philosophyHeading?: T;
  philosophyBody?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  philosophyImageLabel?: T;
  principlesLabel?: T;
  principlesHeading?: T;
  trustLabel?: T;
  trustHeading?: T;
  trustBody?: T;
  trustImageLabel?: T;
  trustButtonLabel?: T;
  founderLabel?: T;
  founderQuote?: T;
  founderSignature?: T;
  ctaHeading?: T;
  ctaBody?: T;
  ctaShopLabel?: T;
  ctaLabLabel?: T;
  complianceText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  siteTitle?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandName?: T;
  brandDescription?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  complianceText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  defaultOGImage?: T;
  logo?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  benefitsLabelTemplate?: T;
  benefitsHeading?: T;
  usageRitualLabel?: T;
  usageRitualHeading?: T;
  usageRitualBody?: T;
  usageRitualDisclaimer?: T;
  verificationLabel?: T;
  verificationHeading?: T;
  verificationBody?: T;
  labReportLabel?: T;
  requestCOALabel?: T;
  completeRitualHeading?: T;
  productDisclaimer?: T;
  collectionLabel?: T;
  supplyLabel?: T;
  purchaseOptionLabel?: T;
  subscribeLabel?: T;
  subscribeDiscountPercent?: T;
  subscribeDetail?: T;
  oneTimeLabel?: T;
  quantityLabel?: T;
  buyNowLabel?: T;
  shippingText?: T;
  ingredientsHeading?: T;
  otherIngredientsText?: T;
  faqLabel?: T;
  faqHeading?: T;
  bankTransferEnabled?: T;
  bankTransferHeading?: T;
  bankTransferNote?: T;
  bankName?: T;
  accountName?: T;
  accountNumber?: T;
  routingNumber?: T;
  swiftCode?: T;
  loginWarning?: T;
  ordersLoginWarning?: T;
  alreadyLoggedInWarning?: T;
  accountHeading?: T;
  recentOrdersHeading?: T;
  recentOrdersDescription?: T;
  noOrdersText?: T;
  viewAllOrdersLabel?: T;
  ordersHeading?: T;
  allOrdersLabel?: T;
  orderNumberPrefix?: T;
  orderDateLabel?: T;
  totalLabel?: T;
  statusLabel?: T;
  itemsLabel?: T;
  itemUnavailableText?: T;
  shippingAddressLabel?: T;
  addressesHeading?: T;
  loginHeading?: T;
  loginDescription?: T;
  createAccountHeading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}